<?php
class JConfig {
	var $offline = '0';
	var $editor = 'none';
	var $list_limit = '20';
	var $helpurl = '';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '1';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret = 'lZRoa1zFj4KSkj7Q';
	var $gzip = '0';
	var $error_reporting = '-1';
	var $xmlrpc_server = '0';
	var $log_path = '/home/c3vanxua/www/logs';
	var $tmp_path = '/home/c3vanxua/www/tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '7';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '21';
	var $ftp_user = '';
	var $ftp_pass = '';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host = 'localhost';
	var $user = 'c3vanxua_6a42o3';
	var $db = 'c3vanxua_v3r17a8';
	var $dbprefix = 'veran7749_';
	var $mailer = 'smtp';
	var $mailfrom = 'quantri@c3vanxuanhd.edu.vn';
	var $fromname = 'Trường THPT Vạn Xuân';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = 'localhost';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '15';
	var $session_handler = 'database';
	var $password = '(5T9~kpV#hM3';
	var $sitename = 'Trường THPT Vạn Xuân';
	var $MetaDesc = 'Trang thông tin Trường THPT Vạn Xuân';
	var $MetaKeys = 'Vạn Xuân, cấp 3 vạn xuân, trung học vạn xuâ, phổ thông vạn xuân, nguyễn trọng thà';
	var $offline_message = 'Chúng tôi đang tạm dừng để nâng cấp nội dung. Chúng tôi sẽ trở lại trong thời gian sớm nhất.Công ty TNHH Veritable.
This site is down for maintenance. Please check back again soon.';
}
?>